[workspace]
# Lien vers le dépôt GitHub pour la création des releases
git_release_enable = false

[[package]]
name = "opensmiles"
# Active la création de GitHub releases et du CHANGELOG pour cette crate
git_release_enable = true
changelog_update = true
# Inclut les PRs de dépendances dans le CHANGELOG
dependencies_update = true

[[package]]
name = "bigsmiles-core"
# Pas encore prêt pour publication
publish = false
git_release_enable = false
changelog_update = false
